
// gif
export const GET_GIF_LOADING = 'GET_GIF_LOADING';
export const GET_GIF_MORE_LOADING = 'GET_GIF_MORE_LOADING';
export const GET_GIF_SUCCESS = 'GET_GIF_SUCCESS';
export const GET_GIF_MORE_SUCCESS = 'GET_GIF_MORE_SUCCESS';
export const GET_GIF_FAIL = 'GET_GIF_FAIL';